export enum CardStatus {
  SOLICITADO = 'SOLICITADO',
  APROVADO = 'APROVADO',
  ENTREGUE = 'ENTREGUE',
  ATIVO = 'ATIVO',
  BLOQUEADO_TEMPORARIO = 'BLOQUEADO_TEMPORARIO',
  BLOQUEADO_PERDA_ROUBO = 'BLOQUEADO_PERDA_ROUBO',
  CANCELADO = 'CANCELADO',
}
